---
- hosts: localhost
  connection: 192.168.0.108
  remote_user: dodo
  tasks:
    - name: deploy nginx docker container
      shell: |
        docker stop hello 
        docker rm -f hello
        docker rmi ravimanickavasagam/hello-java 
        docker run -d -p 80:80 --name hello ravimanickavasagam/hello-java 
